title: "CHLoop"
subtitle: "Simulate spiking neural networks from spatial data"
url: //chloop.github.io

timezone: Europe/Berlin
encoding: utf-8

pygments: true
markdown: rdiscount
rdiscount:
  extensions:
    - footnotes
    - smart

exclude:
    - /**/.git*
    - README.md
    - LICENSE
    - Gemfile*
    - Gruntfile.js
    - Rakefile
    - package.json
    - node_modules
